# FROM ubuntu:20.04

# # タイムゾーンの問い合わせを避けるための設定
# ENV DEBIAN_FRONTEND=noninteractive

# # 必要なツールやライブラリをインストール
# RUN apt-get update && apt-get install -y \
#     gcc \
#     gdb \
#     make \
#     && apt-get clean && rm -rf /var/lib/apt/lists/*
