version: '3.7'
services:
    apache-test:
        image: php:7.4.8-apache
        volumes:
            - "./html/:/var/www/html"
        ports:
            - "4000:80"
        depends_on:
            - mysql
